# .rubocop.yml
AllCops:
  NewCops: enable
  Exclude:
    - "db/schema.rb"
    - "Gemfile"
    - "lib/tasks/*.rake"
    - "bin/*"
    - "config/environments/development.rb"
    - "config/environments/production.rb"
    - "spec/spec_helper.rb"

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Max: 200

Style/FrozenStringLiteralComment:
  Enabled: false