development:
  adapter: postgresql
  encoding: unicode
  database: <%= ENV['DB_NAME'] %>_development
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASS'] %>
  pool: 5
  timeout: 5000
 
test:
  adapter: postgresql
  encoding: unicode
  database: <%= ENV['DB_NAME'] %>_test
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASS'] %>
  pool: 5
  timeout: 5000